### ISSUE TITLE
Convert metric analysis scripts into rust crate

### ISSUE THREAD

**Issue by jonathanpwang** [openvm-org/openvm#1030]
Currently the post-processing on the collected metrics from the prover can processed using python scripts in `ci/scripts/metrics_unify/`. These are used to generate a markdown report and flamegraphs of cell/instruction usage. To keep everything in Rust and also to make it easier to import these tools in other repos, we should convert all the scripts into a Rust crate.

**Comment by keroro520** [comment]
Would you mind to assign this issue to me? @jonathanpwang

**Comment by jonathanpwang** [comment]
Assigned, but noting that I am updating our metrics collection and will be making a first pass at porting over the `summarize.py` because we need it for benchmark analysis

**Comment by jonathanpwang** [comment]
@keroro520 to avoid overlap, you can start with the fine-grained metric collection (corresponding to `metrics_unify/main.py`). I will be focusing on `summarize.py` and `flamegraph.py`.

Separate from this, I would be interested in a standalone prometheus recorder for metrics.
