### ISSUE TITLE
On-Chain Verification on Bitcoin Cash VM

### ISSUE THREAD

**Issue by bitjson** [openvm-org/openvm#1109]
Exciting project, thanks for your work!

**Would you be open to a pull request adding the Bitcoin Cash VM as another target for on-chain proof verification?**

Maybe:

```sh
cargo openvm prove cashvm --input <path_to_input>
cargo openvm verify cashvm --proof <path_to_proof>
```

I can contribute the pull request and help with any maintenance – just want to check with OpenVM maintainers in advance. 

I'd also appreciate any guidance if you already have plans for adding support for other verification targets. The project layout is very clear already (and Contributor Docs are very helpful, thanks!) I'm expecting to simply port the EVM implementations and add another `ProveSubCommand` and `VerifySubCommand`, but just want to make sure I'm working within any existing plans.

**Comment by yi-sun** [comment]
Thanks for the suggestion!  At present we'd prefer not to add a Bitcoin Cash verifier as the maintainers are not sufficiently familiar with the verification model.  We'll revisit in the future if this changes.
